#!/usr/bin/env python3
"""
coverage-report.py — Auto-generate the MITRE ATT&CK coverage matrix from the
rule files themselves, so ATTACK_MATRIX.md never drifts from reality.

Zero-dependency (stdlib only).

It parses every .kql rule under azure-sentinel/, reads the // Technique: and
// Tactic: headers, groups by tactic, and renders a markdown matrix. Hunting
queries under hunting-queries/ are listed in a separate section.

Usage:
    python tools/coverage-report.py            # print report to stdout
    python tools/coverage-report.py --write    # overwrite ATTACK_MATRIX.md
    python tools/coverage-report.py --check     # exit 1 if ATTACK_MATRIX.md is stale

The tactic order follows the MITRE ATT&CK Enterprise kill-chain.
"""
import argparse
import re
import sys
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "azure-sentinel"
HUNTS_DIR = ROOT / "hunting-queries"
MATRIX = ROOT / "ATTACK_MATRIX.md"

# Canonical ATT&CK Enterprise tactic order
TACTIC_ORDER = [
    "Reconnaissance", "Resource Development", "Initial Access", "Execution",
    "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access",
    "Discovery", "Lateral Movement", "Collection", "Command and Control",
    "Exfiltration", "Impact",
]

TECH_RE = re.compile(r'^//\s*Technique:\s*([T0-9.]+)\s*(?:—|-)?\s*(.*)$')
TACTIC_RE = re.compile(r'^//\s*Tactic:\s*(.+)$')


def parse_headers(path: Path) -> dict:
    """Extract technique id/name and tactic(s) from a .kql file header."""
    tech_id, tech_name, tactics = None, "", []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        m = TECH_RE.match(s)
        if m:
            tech_id = m.group(1).strip()
            tech_name = m.group(2).strip()
        m2 = TACTIC_RE.match(s)
        if m2:
            # A rule may list several tactics separated by / or ,
            raw = m2.group(1).strip()
            tactics = [t.strip() for t in re.split(r'[/,]', raw)]
        if tech_id and tactics:
            break
    return {"id": tech_id, "name": tech_name, "tactics": tactics}


def normalize_tactic(t: str) -> str:
    """Map free-form tactic text to a canonical tactic name."""
    tl = t.lower()
    for canon in TACTIC_ORDER:
        if canon.lower() in tl or tl in canon.lower():
            return canon
    # common aliases
    aliases = {
        "cred": "Credential Access", "c2": "Command and Control",
        "privesc": "Privilege Escalation", "lateral": "Lateral Movement",
    }
    for k, v in aliases.items():
        if k in tl:
            return v
    return t  # fall back to as-written


def collect_rules():
    """Return {tactic: [(tech_id, tech_name, rel_path), ...]}."""
    by_tactic = defaultdict(list)
    seen = set()
    for path in sorted(RULES_DIR.rglob("*.kql")):
        h = parse_headers(path)
        if not h["id"]:
            continue
        rel = path.relative_to(ROOT).as_posix()
        # Assign to the FIRST canonical tactic (primary), dedup per (tactic,path)
        primary = normalize_tactic(h["tactics"][0]) if h["tactics"] else "Unknown"
        key = (primary, rel)
        if key in seen:
            continue
        seen.add(key)
        by_tactic[primary].append((h["id"], h["name"], rel))
    return by_tactic


def collect_hunts():
    hunts = []
    if not HUNTS_DIR.exists():
        return hunts
    for path in sorted(HUNTS_DIR.glob("*.kql")):
        h = parse_headers(path)
        rel = path.relative_to(ROOT).as_posix()
        hunts.append((h["id"] or "—", h["name"], rel))
    return hunts


def render(by_tactic, hunts) -> str:
    total_rules = sum(len(v) for v in by_tactic.values())
    covered_tactics = [t for t in TACTIC_ORDER if by_tactic.get(t)]
    all_ids = {tid for items in by_tactic.values() for tid, _, _ in items}

    lines = []
    lines.append("# MITRE ATT&CK Coverage Matrix")
    lines.append("")
    lines.append(f"**Auto-generated by `tools/coverage-report.py`** | "
                 f"**Detection Rules:** {total_rules} | "
                 f"**Hunting Queries:** {len(hunts)} | "
                 f"**Tactics Covered:** {len(covered_tactics)} / {len(TACTIC_ORDER)}")
    lines.append("")
    lines.append("> Do not edit by hand — run `python tools/coverage-report.py --write`.")
    lines.append("")
    lines.append("## Legend")
    lines.append("")
    lines.append("| Status | Meaning |")
    lines.append("|---|---|")
    lines.append("| ✅ | Implemented |")
    lines.append("| ❌ | Not covered |")
    lines.append("")

    for tactic in TACTIC_ORDER:
        lines.append(f"## {tactic}")
        lines.append("")
        items = by_tactic.get(tactic, [])
        lines.append("| Technique | ID | Rule | Status |")
        lines.append("|---|---|---|---|")
        if not items:
            lines.append("| — | — | — | ❌ |")
        else:
            for tid, tname, rel in sorted(items, key=lambda x: x[2]):
                fname = rel.split("/")[-1]
                label = tname or tid
                lines.append(f"| {label} | {tid} | [{fname}]({rel}) | ✅ |")
        lines.append("")

    if hunts:
        lines.append("## Hunting Queries")
        lines.append("")
        lines.append("| Query | Technique | File |")
        lines.append("|---|---|---|")
        for tid, tname, rel in hunts:
            fname = rel.split("/")[-1]
            lines.append(f"| {tname or fname} | {tid} | [{fname}]({rel}) |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"**Tactics covered:** {len(covered_tactics)} / {len(TACTIC_ORDER)}")
    lines.append(f"**Distinct techniques:** {len(all_ids)}")
    lines.append(f"**Detection rules:** {total_rules}  ")
    lines.append(f"**Hunting queries:** {len(hunts)}")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Generate ATT&CK coverage matrix from rules")
    ap.add_argument("--write", action="store_true", help="overwrite ATTACK_MATRIX.md")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if ATTACK_MATRIX.md differs from generated output")
    args = ap.parse_args()

    report = render(collect_rules(), collect_hunts())

    if args.check:
        current = MATRIX.read_text(encoding="utf-8") if MATRIX.exists() else ""
        if current.rstrip("\n") != report.rstrip("\n"):
            print("ATTACK_MATRIX.md is STALE. Run: python tools/coverage-report.py --write")
            sys.exit(1)
        print("ATTACK_MATRIX.md is up to date.")
        sys.exit(0)

    if args.write:
        MATRIX.write_text(report, encoding="utf-8")
        print(f"Wrote {MATRIX.relative_to(ROOT)}")
    else:
        print(report)


if __name__ == "__main__":
    main()
