#!/usr/bin/env python3
"""
terraform-exporter.py — Export KQL detection rules as a Terraform configuration
using the azurerm_sentinel_alert_rule_scheduled resource (Sentinel-as-code).

Zero-dependency (stdlib only).

Generges a single .tf file with one resource block per rule, plus variables for
the workspace/resource-group. Reuses the same header parsing as arm-exporter.

Usage:
    python tools/terraform-exporter.py > sentinel.tf
    python tools/terraform-exporter.py --out deploy/sentinel.tf
    # then: terraform init && terraform apply \
    #         -var 'log_analytics_workspace_id=<id>'
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "azure-sentinel"

TECH_RE = re.compile(r'^//\s*Technique:\s*([T0-9.]+)\s*(?:—|-)?\s*(.*)$')
TACTIC_RE = re.compile(r'^//\s*Tactic:\s*(.+)$')
SEV_RE = re.compile(r'^//\s*Severity:\s*(\w+)')

SENTINEL_TACTICS = {
    "reconnaissance": "Reconnaissance", "resource development": "ResourceDevelopment",
    "initial access": "InitialAccess", "execution": "Execution",
    "persistence": "Persistence", "privilege escalation": "PrivilegeEscalation",
    "defense evasion": "DefenseEvasion", "credential access": "CredentialAccess",
    "discovery": "Discovery", "lateral movement": "LateralMovement",
    "collection": "Collection", "command and control": "CommandAndControl",
    "exfiltration": "Exfiltration", "impact": "Impact",
}
SEV_MAP = {"Critical": "High", "High": "High", "Medium": "Medium",
           "Low": "Low", "Informational": "Informational"}


def parse_meta(text):
    tech_id, tech_name, tactics, sev = "", "", [], "Medium"
    for line in text.splitlines():
        s = line.strip()
        if (m := TECH_RE.match(s)):
            tech_id, tech_name = m.group(1).strip(), m.group(2).strip()
        if (m := TACTIC_RE.match(s)):
            tactics = [t.strip() for t in re.split(r'[/,]', m.group(1))]
        if (m := SEV_RE.match(s)):
            sev = m.group(1).strip()
    return tech_id, tech_name, tactics, sev


def strip_header(text):
    if "// === QUERY ===" in text:
        return text.split("// === QUERY ===", 1)[1].strip()
    return "\n".join(l for l in text.splitlines() if not l.strip().startswith("//")).strip()


def map_tactics(tactics):
    out = [SENTINEL_TACTICS[t.lower()] for t in tactics if t.lower() in SENTINEL_TACTICS]
    return out or ["Execution"]


def tf_ident(stem):
    return re.sub(r'[^a-z0-9_]', '_', stem.lower())


def render_rule(path):
    text = path.read_text(encoding="utf-8")
    tech_id, tech_name, tactics, sev = parse_meta(text)
    query = strip_header(text)
    display = tech_name or path.stem.replace("-", " ").title()
    tactics_hcl = ", ".join(f'"{t}"' for t in map_tactics(tactics))

    return f'''resource "azurerm_sentinel_alert_rule_scheduled" "{tf_ident(path.stem)}" {{
  name                       = "kqllib-{path.stem}"
  log_analytics_workspace_id = var.log_analytics_workspace_id
  display_name               = "[KQL-Lib] {display}"
  severity                   = "{SEV_MAP.get(sev, "Medium")}"
  query_frequency            = "PT1H"
  query_period               = "P1D"
  trigger_operator           = "GreaterThan"
  trigger_threshold          = 0
  tactics                    = [{tactics_hcl}]
  techniques                 = [{f'"{tech_id}"' if tech_id else ""}]

  query = <<-KQL
{query}
KQL
}}'''


def main():
    ap = argparse.ArgumentParser(description="Export rules as Terraform (azurerm Sentinel)")
    ap.add_argument("--out", default="")
    args = ap.parse_args()

    header = '''# Auto-generated by tools/terraform-exporter.py — do not edit by hand.
# Deploy: terraform init && terraform apply -var 'log_analytics_workspace_id=<id>'

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

variable "log_analytics_workspace_id" {
  type        = string
  description = "Resource ID of the Log Analytics workspace with Sentinel enabled"
}
'''
    blocks = [render_rule(p) for p in sorted(RULES_DIR.rglob("*.kql"))]
    out = header + "\n" + "\n\n".join(blocks) + "\n"

    if args.out:
        outp = Path(args.out)
        outp.parent.mkdir(parents=True, exist_ok=True)
        outp.write_text(out, encoding="utf-8")
        print(f"Wrote {len(blocks)} rules to {args.out}", file=sys.stderr)
    else:
        print(out)


if __name__ == "__main__":
    main()
